version: '3'
services:
  redis:
    image: redis:latest
  mysql:
    image: mysql:latest
    ports:
      - 8083:3306
    environment:
      MYSQL_ROOT_PASSWORD: openecoe_1234
      MYSQL_DATABASE: openECOE_dev
      MYSQL_USER: openecoe
      MYSQL_PASSWORD: openecoe
    volumes:
      - ./deploy/data:/docker-entrypoint-initdb.d
    cap_add:
      - SYS_NICE
    healthcheck:
      test: "mysqladmin ping -p$$MYSQL_ROOT_PASSWORD"
      timeout: 5s
      retries: 3
  api:
    image: openecoe/api:latest
    ports:
      - 8081:5000
    environment:
      # Data for first run if no organization created
      EMAIL: ecoe@umh.es
      PASSWORD: Ki0uchee
      FIRSTNAME: Open
      SURNAME: ECOE
      ORGANIZATION: UMH
      #API Configuration
      SERVER_NAME: openecoe
      SECRET_KEY: eiQuain4_aelohKa3_giGh6Fai_reeTh6Ai_Aegeic6l_ekuigo0M_aeph6Qua_uuZaac5n
      BCRYPT_LOG_ROUNDS: 4
      DEBUG: "False"
      TESTING: "False"
      LOG_TO_STDOUT: "True"
      SQLALCHEMY_TRACK_MODIFICATIONS: "False"
      API_AUTH: "True"
      SQLALCHEMY_DATABASE_URI: mysql+pymysql://openecoe:openecoe@mysql/openECOE_dev
      RQ_REDIS_URL: redis://redis:6379/0
    depends_on:
      redis:
        condition: service_started
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/status/"]
      interval: 30s
      timeout: 10s
      retries: 3
  worker:
    image: openecoe/api:latest
    entrypoint: [ "flask", "rq", "worker"]
    environment:
      RQ_REDIS_URL: redis://redis:6379/0
    depends_on:
      api:
        condition: service_healthy
  web:
    image: openecoe/webui:latest
    environment:
      SECRET_KEY: eiQuain4_aelohKa3_giGh6Fai_reeTh6Ai_Aegeic6l_ekuigo0M_aeph6Qua_uuZaac5n
      DEBUG: "True"
      API_URL: http://localhost:8081
      CHRONO_ROUTE: http://localhost:8081/chrono
    ports:
      - 8080:80