version: '3'
services:
  redis:
    image: redis:latest
  mysql:
    image: mysql:latest
    ports:
      - 8083:3306
    environment:
      MYSQL_ROOT_PASSWORD: openecoe_1234
      MYSQL_DATABASE: openECOE_dev
      MYSQL_USER: openecoe
      MYSQL_PASSWORD: openecoe
    volumes:
      - ./deploy/data:/docker-entrypoint-initdb.d
    cap_add:
      - SYS_NICE
    healthcheck:
      test: "mysqladmin ping -p$$MYSQL_ROOT_PASSWORD"
      timeout: 5s
      retries: 3
  api:
    image: openecoe/api:latest
    ports:
      - 8081:5000
    environment:
      #API Configuration
      OPENECOE_SECRET: eiQuain4_aelohKa3_giGh6Fai_reeTh6Ai_Aegeic6l_ekuigo0M_aeph6Qua_uuZaac5n
      OPENECOE_DB_HOST: db
      OPENECOE_DB_PORT: 3306
      OPENECOE_DB_USER: openecoe
      OPENECOE_DB_PASSWORD: openecoe_pass
      OPENECOE_DB_NAME: openECOE
      OPENECOE_REDIS_HOST: redis
      OPENECOE_REDIS_PORT: 6379
      OPENECOE_REDIS_DB: 0
      # Data for first run if no organization created
      EMAIL: ecoe@umh.es
      PASSWORD: Ki0uchee
      FIRSTNAME: Open
      SURNAME: ECOE
      ORGANIZATION: UMH
    depends_on:
      redis:
        condition: service_started
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/status/"]
      interval: 30s
      timeout: 10s
      retries: 3
  web:
    image: openecoe/webui:latest
    environment:
      BACKEND_ROUTE: http://localhost:8081
    ports:
      - 8080:80