version: '3'
services:
  redis:
    image: redis:latest
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: openecoe_1234
      MYSQL_DATABASE: openECOE
      MYSQL_USER: openecoe
      MYSQL_PASSWORD: openecoe_pass
    cap_add:
      - SYS_NICE
    healthcheck:
      test: "mysqladmin ping -p$$MYSQL_ROOT_PASSWORD"
      timeout: 5s
      retries: 3
  openecoe:
    build: 
      context: .
      dockerfile: Dockerfile
    image: openecoe/one-for-all:latest
    ports:
      - 8081:80
    environment:
      OPENECOE_SECRET: eiQuain4_aelohKa3_giGh6Fai_reeTh6Ai_Aegeic6l_ekuigo0M_aeph6Qua_uuZaac5n
      OPENECOE_DB_HOST: db
      OPENECOE_DB_PORT: 3306
      OPENECOE_DB_USER: openecoe
      OPENECOE_DB_PASSWORD: openecoe_pass
      OPENECOE_DB_NAME: openECOE
      OPENECOE_REDIS_HOST: redis
      OPENECOE_REDIS_PORT: 6379
      OPENECOE_REDIS_DB: 0
      
      # Usuario por defecto creado la primera vez
      EMAIL: ecoe@umh.es
      PASSWORD: Kui0chee
      FIRSTNAME: Open
      SURNAME: ECOE
      ORGANIZATION: UMH
      ALEMBIC_UPGRADE: DO

      # Configruación debug
      DEBUG: "False"
      LOG_TO_STDOUT: "False"
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy